### PR TITLE
UofT DSI | Applying Statistical Concepts - Assignment 1 (KNN Classification on wine)

### PR DESCRIPTION
**Pull request by lee-data**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
I added a plot on cross-validation accuracies grid - for my own ref. 

NOTE: To view details on my lessons learned/challenges, please refer to the CLOSED PULL REQUEST. 

## What did you learn from the changes you have made?
I actually learnt that using NP.RANDOM.SEED(123) is more appropriate than the given code RANDOM.SEED(123) because the following given split code uses numpy arrays, which means the given RANDOM.SEED(123) does not work, and different numbers sequence are generated every time the notebook is re-run. 

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
Yes - see above. 

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
Yes - see above. 

## How were these changes tested?
In VS Code - Jupyter notebook

## A reference to a related issue in your repository (if applicable)
N/A 

## Checklist
- [X] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by lee-data** [comment]
Closing the Pull Request in order to create a new one with the bug "np.random.seed(123)" agreed to be corrected by the school.

**Comment by lee-data** [comment]
reopening the pull request as i had closed it accidentally before having it approved/saved down.

**Comment by lee-data** [comment]
fixed bug - using np.random.seed(123) instead of random.seed(123)

**Review by amanda-ng518 — APPROVED** [review]
A1 PASS

**Comment by lee-data** [comment]
> A1 PASS

Thank you Amanda, I will close the pull request now.

**Pull request closed without merging**
